# Generated by Django 3.2.25 on 2026-05-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobExecutionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('search', 'Search files'), ('backup', 'Backup files'), ('plan', 'Execute plan')], max_length=16)),
                ('bk_biz_id', models.IntegerField(default=0)),
                ('bk_host_ids', models.CharField(default='', max_length=512)),
                ('job_plan_id', models.IntegerField(default=0)),
                ('job_instance_id', models.BigIntegerField(default=0)),
                ('job_instance_name', models.CharField(default='', max_length=255)),
                ('step_instance_id', models.BigIntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('status_text', models.CharField(default='unknown', max_length=64)),
                ('search_path', models.CharField(default='', max_length=1024)),
                ('suffix', models.CharField(default='', max_length=64)),
                ('backup_path', models.CharField(default='', max_length=1024)),
                ('job_url', models.CharField(default='', max_length=512)),
                ('result_summary', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
