# Generated by Django 3.2.25 on 2026-05-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_category', models.CharField(max_length=64)),
                ('api_name', models.CharField(max_length=128)),
                ('request_count', models.IntegerField(default=0)),
                ('last_username', models.CharField(default='', max_length=150)),
                ('last_path', models.CharField(default='', max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('api_category', 'api_name'),
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='anonymous', max_length=150)),
                ('api_category', models.CharField(max_length=64)),
                ('api_name', models.CharField(max_length=128)),
                ('method', models.CharField(max_length=12)),
                ('path', models.CharField(max_length=512)),
                ('status_code', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='userbehaviorevent',
            index=models.Index(fields=['api_category', 'api_name'], name='analytics_u_api_cat_0ed22f_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehaviorevent',
            index=models.Index(fields=['username', 'created_at'], name='analytics_u_usernam_264a5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apirequestcount',
            unique_together={('api_category', 'api_name')},
        ),
    ]
